In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('/content/Mobile Reviews Sentiment null.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   review_id             50000 non-null  int64
 1   customer_name         50000 non-null  object
 2   age                   50000 non-null  int64
 3   brand                 50000 non-null  object
 4   model                 50000 non-null  object
 5   price_usd             47550 non-null  float64
 6   price_local           47569 non-null  object
 7   currency              50000 non-null  object
 8   exchange_rate_to_usd  50000 non-null  float64
 9   rating                47547 non-null  float64
 10  sentiment             47555 non-null  object
 11  country               50000 non-null  object
 12  language              50000 non-null  object
 13  review_date           50000 non-null  object
 14  verified_purchase     50000 non-null  bool
 15  battery_life_rating   50000 non-null  int64
 16  camera_rating         50000 non-null  int64
 17  performance_rating    50000 non-null  int64
 18  design_rating         50000 non-null  int64
 19  display_rating        50000 non-null  int64
 20  helpful_votes         50000 non-null  int64
 21  source                47552 non-null  object
dtypes: bool(1), float64(3), int64(8), object(10)
memory usage: 8.1+ MB

In [4]:
df.shape

(50000, 22)

In [5]:
df.head()

,review_id,customer_name,age,brand,model,price_usd,price_local,currency,exchange_rate_to_usd,rating,...,language,review_date,verified_purchase,battery_life_rating,camera_rating,performance_rating,design_rating,display_rating,helpful_votes,source
0,1,Aryan Maharaj,45,Realme,Realme 12 Pro,337.31,₹27996.73,INR,83.00,2.0,...,Hindi,11/6/2023,True,1,1,3,2,1,1,Amazon
1,2,Davi Miguel Sousa,18,Realme,Realme 12 Pro,307.78,R$1754.35,BRL,5.70,4.0,...,Portuguese,3/30/2023,True,3,2,4,3,2,5,Flipkart
2,3,Pahal Balay,27,Google,Pixel 6,864.53,₹71755.99,INR,83.00,4.0,...,Hindi,12/7/2022,True,3,5,3,2,4,8,AliExpress
3,4,David Guzman,19,Xiaomi,Redmi Note 13,660.94,د.إ2425.65,AED,3.67,3.0,...,English,3/11/2025,False,1,3,2,1,2,3,Amazon
4,5,Yago Leão,38,Motorola,Edge 50,792.13,R$4515.14,BRL,5.70,3.0,...,Portuguese,9/29/2023,True,3,3,2,2,1,0,BestBuy

In [6]:
df.tail()

,review_id,customer_name,age,brand,model,price_usd,price_local,currency,exchange_rate_to_usd,rating,...,language,review_date,verified_purchase,battery_life_rating,camera_rating,performance_rating,design_rating,display_rating,helpful_votes,source
49995,49996,Rebecca Pratt,18,Realme,Realme 12 Pro,526.10,A$804.93,AUD,1.53,4.0,...,English,8/17/2023,False,3,3,4,3,5,4,BestBuy
49996,49997,Dr. Tiffany Patterson,28,Samsung,Galaxy Note 20,911.85,A$1395.13,AUD,1.53,3.0,...,English,9/23/2023,False,3,2,4,1,3,2,AliExpress
49997,49998,Alexandra Singh,21,Apple,iPhone SE,1155.32,د.إ4240.02,AED,3.67,NaN,...,English,4/4/2023,True,2,3,4,4,5,4,Amazon
49998,49999,Robert Morris,31,Realme,Realme Narzo 70,459.04,NaN,USD,1.00,3.0,...,English,7/11/2025,True,1,2,2,1,3,6,NaN
49999,50000,Regina Dennis MD,44,Motorola,Moto G Power,380.16,$380.16,USD,1.00,5.0,...,English,11/26/2024,True,4,5,4,5,3,7,BestBuy

In [7]:
df.isnull().sum()/df.shape[0]*100

review_id               0.000
customer_name           0.000
age                     0.000
brand                   0.000
model                   0.000
price_usd               4.900
price_local             4.862
currency                0.000
exchange_rate_to_usd    0.000
rating                  4.906
sentiment               4.890
country                 0.000
language                0.000
review_date             0.000
verified_purchase       0.000
battery_life_rating     0.000
camera_rating           0.000
performance_rating      0.000
design_rating           0.000
display_rating          0.000
helpful_votes           0.000
source                  4.896
dtype: float64

###fixing missing values in price

In [8]:
df["price_usd"].median()

637.585

In [9]:
df.groupby(["brand", "model"])["price_usd"].median()

brand     model
Apple     iPhone 13          1106.380
          iPhone 14          1094.510
          iPhone 15 Pro      1102.270
          iPhone SE          1101.030
Google    Pixel 6             808.530
          Pixel 7a            809.440
          Pixel 8             799.520
Motorola  Edge 50             514.920
          Moto G Power        505.340
          Razr 40             511.440
OnePlus   OnePlus 11R         667.025
          OnePlus 12          668.090
          OnePlus Nord 3      669.400
Realme    Realme 12 Pro       396.410
          Realme Narzo 70     392.820
Samsung   Galaxy A55          908.740
          Galaxy Note 20      905.775
          Galaxy S24          888.435
          Galaxy Z Flip       905.380
Xiaomi    Mi 13 Pro           443.830
          Poco X6             451.600
          Redmi Note 13       450.800
Name: price_usd, dtype: float64

In [10]:
df.groupby(["brand", "model"])["price_usd"].agg(["count", "mean", "median"])

                          count         mean    median
brand    model
Apple    iPhone 13         1683  1106.216589  1106.380
         iPhone 14         1694  1102.027704  1094.510
         iPhone 15 Pro     1700  1100.782200  1102.270
         iPhone SE         1715  1103.598758  1101.030
Google   Pixel 6           2274   808.631768   808.530
         Pixel 7a          2347   807.655334   809.440
         Pixel 8           2282   799.029890   799.520
Motorola Edge 50           2213   509.784546   514.920
         Moto G Power      2228   503.959511   505.340
         Razr 40           2288   505.917338   511.440
OnePlus  OnePlus 11R       2310   673.023320   667.025
         OnePlus 12        2200   670.238523   668.090
         OnePlus Nord 3    2249   673.148079   669.400
Realme   Realme 12 Pro     3341   394.327411   396.410
         Realme Narzo 70   3422   392.155240   392.820
Samsung  Galaxy A55        1703   906.946676   908.740
         Galaxy Note 20    1700   900.871253   905.775
         Galaxy S24        1674   895.131099   888.435
         Galaxy Z Flip     1633   898.912823   905.380
Xiaomi   Mi 13 Pro         2318   449.180155   443.830
         Poco X6           2239   450.490536   451.600
         Redmi Note 13     2337   449.615434   450.800

In [11]:
#transforming the groupby price with median
df["price_usd"] = df["price_usd"].fillna(df.groupby(["brand", "model"])["price_usd"].transform("median"))

In [12]:
#filling the overall price with median
df["price_usd"] = df["price_usd"].fillna(df["price_usd"].median())

In [13]:
df.isnull().sum()/df.shape[0]*100

review_id               0.000
customer_name           0.000
age                     0.000
brand                   0.000
model                   0.000
price_usd               0.000
price_local             4.862
currency                0.000
exchange_rate_to_usd    0.000
rating                  4.906
sentiment               4.890
country                 0.000
language                0.000
review_date             0.000
verified_purchase       0.000
battery_life_rating     0.000
camera_rating           0.000
performance_rating      0.000
design_rating           0.000
display_rating          0.000
helpful_votes           0.000
source                  4.896
dtype: float64

In [14]:
#price local column is redundant and not uniform, dropping it from the df
df = df.drop(["price_local"], axis=1)

In [15]:
df.dtypes

review_id                 int64
customer_name            object
age                       int64
brand                    object
model                    object
price_usd               float64
currency                 object
exchange_rate_to_usd    float64
rating                  float64
sentiment                object
country                  object
language                 object
review_date              object
verified_purchase          bool
battery_life_rating       int64
camera_rating             int64
performance_rating        int64
design_rating             int64
display_rating            int64
helpful_votes             int64
source                   object
dtype: object

##Fixing Missing Values in Rating

In [16]:
df["rating"].median()

3.0

In [18]:
df.groupby(["brand", "model"])["rating"].median()

brand     model
Apple     iPhone 13          3.0
          iPhone 14          3.0
          iPhone 15 Pro      3.0
          iPhone SE          3.0
Google    Pixel 6            3.0
          Pixel 7a           3.0
          Pixel 8            3.0
Motorola  Edge 50            3.0
          Moto G Power       3.0
          Razr 40            3.0
OnePlus   OnePlus 11R        3.0
          OnePlus 12         3.0
          OnePlus Nord 3     3.0
Realme    Realme 12 Pro      3.0
          Realme Narzo 70    3.0
Samsung   Galaxy A55         3.0
          Galaxy Note 20     3.0
          Galaxy S24         3.0
          Galaxy Z Flip      3.0
Xiaomi    Mi 13 Pro          3.0
          Poco X6            3.0
          Redmi Note 13      3.0
Name: rating, dtype: float64

In [20]:
#transforming the groupby ratings with median

df["rating"] = df["rating"].fillna(df.groupby(["brand", "model"])["rating"].transform("median"))

In [21]:
#filling the overall rating with median

df["rating"] = df["rating"].fillna(df["rating"].median())

##Fixing Missing Values in Sentiment rating

In [25]:
#cateogircal colum, hence fill with mode
def map_sentiment(rating):
    if rating >= 4:
        return "Positive"
    elif rating == 3:
        return "Neutral"
    else:
        return "Negative"

mask = df["sentiment"].isnull()

df.loc[mask, "sentiment"] = df.loc[mask, "rating"].apply(map_sentiment)

print('Remaining missing values: ', df["sentiment"].isna().sum())

Remaining missing values:  0

##Filling Missing values in Source

In [26]:
df.source.mode()

0    eBay
Name: source, dtype: object

In [30]:
df["source"] = df["source"].fillna(df["source"].mode())

In [31]:
df.isnull().sum()

review_id               0
customer_name           0
age                     0
brand                   0
model                   0
price_usd               0
currency                0
exchange_rate_to_usd    0
rating                  0
sentiment               0
country                 0
language                0
review_date             0
verified_purchase       0
battery_life_rating     0
camera_rating           0
performance_rating      0
design_rating           0
display_rating          0
helpful_votes           0
source                  0
dtype: int64

In [32]:
df.duplicated().sum()

np.int64(0)

##fixing date

In [38]:
dash = df["review_date"].str.contains("-")
slash = df["review_date"].str.contains("/")

In [39]:
df.loc[dash, "review_date"] = pd.to_datetime(df.loc[dash, "review_date"], format="%d-%m-%Y")

df.loc[slash, "review_date"] = pd.to_datetime(df.loc[slash, "review_date"], format="%m/%d/%Y")

In [40]:
df["review_date"].isna().sum()

np.int64(0)

In [43]:
df["review_date"] = pd.to_datetime(df["review_date"]).dt.date

In [44]:
df.review_date

0        2023-11-06
1        2023-03-30
2        2022-12-07
3        2025-03-11
4        2023-09-29
            ...
49995    2023-08-17
49996    2023-09-23
49997    2023-04-04
49998    2025-07-11
49999    2024-11-26
Name: review_date, Length: 50000, dtype: object

##checking the cleaned data for final save

In [45]:
df.dtypes

review_id                 int64
customer_name            object
age                       int64
brand                    object
model                    object
price_usd               float64
currency                 object
exchange_rate_to_usd    float64
rating                  float64
sentiment                object
country                  object
language                 object
review_date              object
verified_purchase          bool
battery_life_rating       int64
camera_rating             int64
performance_rating        int64
design_rating             int64
display_rating            int64
helpful_votes             int64
source                   object
dtype: object

In [46]:
df.isnull().sum()/df.shape[0]*100

review_id               0.0
customer_name           0.0
age                     0.0
brand                   0.0
model                   0.0
price_usd               0.0
currency                0.0
exchange_rate_to_usd    0.0
rating                  0.0
sentiment               0.0
country                 0.0
language                0.0
review_date             0.0
verified_purchase       0.0
battery_life_rating     0.0
camera_rating           0.0
performance_rating      0.0
design_rating           0.0
display_rating          0.0
helpful_votes           0.0
source                  0.0
dtype: float64

In [47]:
df.to_csv('Mobile Reviews_cleaned.csv', index = False)